### ISSUE TITLE
multiuser demo

### ISSUE THREAD

**Issue by lazydino** [virtual-world-framework/vwf-apps#21]
Hi, 

I clone the repos and run it with VWF  at https://github.com/virtual-world-framework/vwf , most of the demos are working, but when I try 'multiuser', Node JS reports:

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at Object._404 (c:\Users\Reggie\Documents\vwf_full\lib\nodejs\serve.js:41:18)
    at Object.Serve (c:\Users\Reggie\Documents\vwf_full\lib\nodejs\vwf.js:143:15)
    at Server.OnRequest (c:\Users\Reggie\Documents\vwf_full\node_vwf.js:106:17)
    at Manager.handleRequest (c:\Users\Reggie\Documents\vwf_full\node_modules\socket.io\lib\manager.js:565:28)
    at Server.<anonymous> (c:\Users\Reggie\Documents\vwf_full\node_modules\socket.io\lib\manager.js:119:10)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming](_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)

Both vwf and vwf-apps are checked out at 'master' branch, vwf-apps is checked out at public/vwf-apps. How can I make it run like https://demo.virtual.wf/demos/multiuser/ ?

**Comment by scottnc27603** [comment]
I'll take a look at this.  Which branch are you using?

**Comment by lazydino** [comment]
Both at master

**Comment by lazydino** [comment]
Both at master

**Comment by lazydino** [comment]
Both set to 'master'

**Comment by scottnc27603** [comment]
I'm not seeing this problem.  Where did you copy the error message above from?

What version of node js are you using?

**Comment by lazydino** [comment]
node ---version shows 'v0.12.2' The repos is cloned at vwf-apps folder under public. I am running Chrome on Win 8.1.  http://localhost:3000/public/vwf-apps/multiuser causes the following error

Reggie@MAGNETO ~/Documents/vwf_full (master)
$ node node-server
LogLevel = 1
Serving VWF support files from c:\Users\Reggie\Documents\vwf_full
Serving VWF applications from c:\Users\Reggie\Documents\vwf_full
Serving on port 3000
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at Object._404 (c:\Users\Reggie\Documents\vwf_full\lib\nodejs\serve.js:41:18)
    at Object.Serve (c:\Users\Reggie\Documents\vwf_full\lib\nodejs\vwf.js:143:15)
    at Server.OnRequest (c:\Users\Reggie\Documents\vwf_full\node_vwf.js:106:17)
    at Manager.handleRequest (c:\Users\Reggie\Documents\vwf_full\node_modules\socket.io\lib\manager.js:565:28)
    at Server.<anonymous> (c:\Users\Reggie\Documents\vwf_full\node_modules\socket.io\lib\manager.js:119:10)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming](_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
![vwfapp-err](https://cloud.githubusercontent.com/assets/1158846/9140410/e82f9a1c-3ce5-11e5-8bf4-61571f92b60b.png)

**Comment by scottnc27603** [comment]
Have you tried starting the server with 'npm start'?

**Comment by lazydino** [comment]
Thanks, so it is a issue of not specifying applicationPath at my end, It works now with localhost:3100/vwf-apps/multiuser .
